### ISSUE TITLE
Missing the possibility of adding interceptors

### ISSUE THREAD

**Issue by pszerszen** [PawelAdamski/HttpClientMock#15]
Currently, interceptors behavior has to be faked for each end every mocked request. If a dev decides to use interceptors on the actual HttpClient, he/she needs to code a lot for the sake of tests.
The very same interceptors (same interfaces) should be possible to add to the HttpClientMock class via builder - just like [HttpClientBuilder's methods](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html):
```
HttpClientBuilder.addInterceptorFirst(org.apache.http.HttpRequestInterceptor itcp)
HttpClientBuilder.addInterceptorFirst(org.apache.http.HttpResponseInterceptor itcp)
HttpClientBuilder.addInterceptorLast(org.apache.http.HttpRequestInterceptor itcp)
HttpClientBuilder.addInterceptorLast(org.apache.http.HttpResponseInterceptor itcp)
```

**Comment by PawelAdamski** [comment]
Fixed in version 1.6.0.
Methods: `addRequestInterceptor` and `addResponseInterceptors` were added.
