### ISSUE TITLE
Matching should ignore redundant or additional parameters

### ISSUE THREAD

**Issue by tvinke** [PawelAdamski/HttpClientMock#23]
Hi Pawel,

Thank you for your awesome library, it has has brought great value in numerous projects already. 👍🏻Hence, dare I make a feature request? 

## Problem

**For some of my use cases the matching of an URL is _too strict_.** If the actual URL contains any parameters, it seems I have to record expectations with exactly the their names, or they won't match. 

Hopefully an example will illustrate my point. I created following locally in the same style as other tests in your `HttpClientMockBuilderTest` to demonstrate the use case I'd like to work.
```
  @Test
  public void should_match_any_parameter_value() throws IOException {
    HttpClientMock httpClientMock = new HttpClientMock("http://localhost:8080");

    httpClientMock
            .onGet("/foo")
            .doReturn("whatever");

    HttpResponse one = httpClientMock.execute(new HttpGet("http://localhost:8080/foo?id=1&name=abc"));
    HttpResponse two = httpClientMock.execute(new HttpGet("http://localhost:8080/foo?id=2"));

    assertThat(one, hasStatus(200));
    assertThat(two, hasStatus(200));
  }
```
As no other you know why this test actually fails with 404's ;-) The debug output shows some of the conditions don't match:
```
Request: GET http://localhost:8080/foo?id=1&name=abc
Rule 1:
	MATCHES		EXPECTED
	true		HTTP method is GET
	true		schema is "http"
	true		host is "localhost"
	true		path is "/foo"
	true		port is <8080>
	false		parameter id is redundant
	false		parameter name is redundant

----------------
Request: GET http://localhost:8080/foo?id=2
Rule 1:
	MATCHES		EXPECTED
	true		HTTP method is GET
	true		schema is "http"
	true		host is "localhost"
	true		path is "/foo"
	true		port is <8080>
	false		parameter id is redundant
```

"parameter id is redundant". By default, when actual parameters "id" and "name" are present, none of the rules match, because I didn't explicitly specify them.

A naive solution seems to be listing each and every possible parameter by name, ignoring whatever value they have, such as:
```
httpClientMock
    .onGet("/foo")
    .withParameter("id", Matchers.any(String.class))
    .withParameter("name", Matchers.any(String.class))
    .doReturn("whatever");
```
but now the 2nd request `http://localhost:8080/foo?id=2` fails, because "parameter name occurs in request". 

In my primary use case above, **I want any request on `/foo` to match (and return "whatever"), no matter the parameters.** 
* I don't care about the parameters for some of my tests, and I'd rather not have to specify them by name at all if I don't have too.
* Right now I'm forced to "duplicate" multiple mock requests just because of the variation of parameters which sometimes are not relevant at all.

_I have not found a way to ignore any redundant or additional parameters, so if there ís I hope you can point me in the right direction and skip the rest of my request below_ :-)

## Feature request

Could you allow me in my tests to match parameters more leniently and give me the option to ignore redundant/additional parameters?

## Suggestion 

Making the _default behaviour_ of HttpClientMock with regard to parameter matching more lenient is due to backwards-compatibility concerns not advisable, but maybe this can be specified either on the mock itself, or as part of the conditions, to enable the desired behaviour **of not failing on irrelevant parameters**.

E.g. to make above test pass, one could use a new `withAnyParameter` method:
```
httpClientMock
        .onGet("/foo")
        .withAnyParameter()
        .doReturn("whatever");
```
(allowing in the future additional similar methods e.g. `withAnyReference` etc.)

Or there could be an option to **match on the name of a parameter with a Hamcrest matcher**, by introducing a `withParameter(Matcher<String> nameMatcher)` allowing to match the existince something specific or -- in my case -- "anything".
```
httpClientMock
    .onGet("/foo")
    .withParameter(Matchers.any(String.class))
    .doReturn("whatever");
```
In this case you'd still have a parameter condition under the hood.

In any case, you'd have to see whatever doesn't interfere too much with the existing underlying rule-matching logic. I'm happy to think along, if you need to! 👍

**Comment by PawelAdamski** [comment]
Hi @tvinke 
I appreciate your kind words about my project. They make me more motivated to continue to work on it.

Regarding your issue, my idea was that you should be able to achieve a more lenient matching by defining rules for each part of URL separately. By my design the following test should pass:
```
public void shouldNotAddUrlConditions_whenUrlWasNotProvided() throws IOException {
    HttpClientMock httpClientMock = new HttpClientMock();
    httpClientMock.onGet()
        .withPath("/foo")
        .doReturn("whatever");

    HttpResponse one = httpClientMock.execute(new HttpGet("http://localhost:8080/foo?id=1&name=abc"));
    HttpResponse two = httpClientMock.execute(new HttpGet("http://localhost:8080/foo?id=2"));

    assertThat(one, hasStatus(200));
    assertThat(two, hasStatus(200));
  }
```
Unfortunately, it doesn't, it turned out that I have a bug in class UrlConditions and the above test fails. I will try to find some time and fix that soon.

**Comment by tvinke** [comment]
> By my design the following test should pass

Exactly!

> it turned out that I have a bug in class UrlConditions. I will try to find some time and fix that soon.

Much appreciated!

**Comment by PawelAdamski** [comment]
Hi @tvinke 
Finally, I found some time to work on that issue.
Since version 1.8.0 you can control the matching of extra parameters using methods `withExtraParameters` and `withoutExtraParameters`.

What is more, I decided to break backward compatibility and since 1.8.0 by default HttpClientMock matches request with extra form or query parameters.

**Comment by tvinke** [comment]
Hi @PawelAdamski I will give it a try shortly!
