### ISSUE TITLE
Apache HTTP Client 5

### ISSUE THREAD

**Issue by ryber** [PawelAdamski/HttpClientMock#26]
Hello! 

 Do you have any plans to support Apache Http Client 5? I realize it's a bid deal as it rewrites huge chunks.

Thanks for the great library BTW I use it all the time,

Ryan

**Comment by PawelAdamski** [comment]
Hi @ryber 

Thank you for you kind words about my project. I'm very happy that it is helpful for you.

Yes, I have a plan to support Http Client 5. I even thought about making my project an official test library for HttpClient 5. I already had small conversation with HttpClient developers but so far nothing was decided.

**Comment by johnksv** [comment]
Hi,

Any updates on this?

Also, thank you for a great project!

**Comment by PawelAdamski** [comment]
Today I've tried to migrate library to the Http Client 5 and it seems that most of the work is just about changing the packages. If there will no unexpected problems I should be able to finish the migration by the end of this week.

**Comment by PawelAdamski** [comment]
I have prepared a version of the library compatible with HttpClient 5.
You can find it on branch master_v5.
It would be very helpful if you could have a look at it and try it on your projects.
In the next few days, it should be also available from Maven.

**Comment by johnksv** [comment]
I can confirm that my tests passed using the master_v5-branch-snapshot.
Thank you very much.

**Comment by PawelAdamski** [comment]
You can find it also in Maven Central Repository.
https://mvnrepository.com/artifact/com.github.paweladamski/HttpClient5Mock/1.0.0-RC1 
If I won't find any bugs in 1.0.0-RC1 I will release version 1.0.0 in about two weeks. I don't expect any changes in the API during that time.

**Comment by PawelAdamski** [comment]
I've decided to use the same artifactId.
* For mocking HttpClient 4.x use HttpClientMock 1.X.
* For mocking HttpClient 5.x use HttpClientMock 2.X.
