### ISSUE TITLE
Unable to reset stubs between tests

### ISSUE THREAD

**Issue by GuyJackson** [PawelAdamski/HttpClientMock#27]
Thank you for all your work on this project. Much easier and more intuitive than hacking around with mockito (in this case).

I'm currently having an issue of rules defined in one test being picked up by others tests. For example I might have a test like this:

```
 @Test
      void some_test_1() {

        httpClientMock.onGet()
            .withPath(containsString("cars"))
            .doReturn("")
            .withStatus(404);

       // request to some other service that would eventually call httpClientMock
        var response = testRestTemplate.exchange(
            "/v001/someOtherServicePath",
            HttpMethod.GET,
            null,
            String.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
      }
```

and another test:

```
 @Test
      void some_test_2() {

        httpClientMock.onGet()
            .withPath(containsString("cars"))
            .doReturn("")
            .withStatus(503);

       // request to some other service that would eventually call httpClientMock
        var response = testRestTemplate.exchange(
            "/v001/someOtherServicePath",
            HttpMethod.GET,
            null,
            String.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.SERVICE_UNAVAILABLE);
      }
```

matching rules output, might look like this (NB I know this is showing the rules don't match in this case - I'm just highlighting that 2 rules appear from different tests...)

> Rule 1:
> 	MATCHES		EXPECTED
> 	false		HTTP method is GET
> 	true		schema is an instance of java.lang.String
> 	true		host is 
> 	false		path is a string containing "cars"
> 	true		port is empty
> Rule 2:
> 	MATCHES		EXPECTED
> 	false		HTTP method is GET
> 	true		schema is an instance of java.lang.String
> 	true		host is 
> 	false		path is a string containing "cars"
> 	true		port is empty

Using `httpClientMock.reset()` via a `BeforeEach` does not appear to make any difference.

When I run the tests individually they pass as expected however when I run them altogether via maven or in intellij they fail, as unrequired rules and stubs seem to be picked up from others tests.

I'm using spring boot `@SpringBootTest` and have `HttpClientMock` autowired in as a bean.

Any help/advice appreciated.

**Comment by PawelAdamski** [comment]
Hi
I'm happy that you enjoy work with my library. The reason why I've created it was exactly what you wrote. Mocking HttpClient with Mockito is so painful. 

Regarding your issue. It is a bug, I'm surprised that so far nobody has spotted it. I guess most of the people create a new instance of HttpClientMock for each test. 

I've fixed it in #28

**Comment by GuyJackson** [comment]
Thanks Paweł - appreciate you looking at this so quickly!

**Comment by PawelAdamski** [comment]
@GuyJackson Please try with version 1.8.1, it should fix your problem.

**Comment by GuyJackson** [comment]
Works as expected. Thanks again.
