### ISSUE TITLE
How can reture HTTP status message

### ISSUE THREAD

**Issue by abhikt48** [PawelAdamski/HttpClientMock#29]
Hi Team,

I need to return specific HTTP status message instead of default **ok**.

E.g - 1. 409 - Conflict 
2. 400 Bad Request

i tried wth below code snippet but is returning 'ok' instead of 'conflict' while calling `getStatusText()` operation,.

`httpClientMock.onPost("testUlr").doReturn(409, "some message");`

Could you please suggest any way to set status text as well?

**Comment by abhikt48** [comment]
I got one alternative for this problem to use Action. It is working fine for me.

Recomendation - I must recommend you to provide one `doReturn ` override method which should accept status text as well.

**Comment by PawelAdamski** [comment]
Hi @abhikt48 
You are right currently the only way to set statusText is by using "Action".
To make that easier I will extend the method `withStatus` to accept `reason` parameter.

So the full usage will look like that:
httpClientMock.onPost("testUlr").doReturn("some message").withStatus(409,"reason");

**Comment by PawelAdamski** [comment]
Will be fixed in the scope of https://github.com/PawelAdamski/HttpClientMock/issues/33
