### ISSUE TITLE
Clear all mocked calls

### ISSUE THREAD

**Issue by pkalbrun-goeuro** [PawelAdamski/HttpClientMock#3]
It would be nice to have a feature to clear all mocked calls - reset state.

**Comment by PawelAdamski** [comment]
Please describe use case. I would rather prefer to avoid it.

**Comment by pkalbrun-goeuro** [comment]
Use case:
Spring test configuration, httpclientmock as one of the singleton beans, autowired.
We are using this httpclient to mock different responses in different tests cases. 
This feature would be useful to do in before and after callbacks during the test.

**Comment by PawelAdamski** [comment]
Fixed in version 0.6.0
