### ISSUE TITLE
Java 11 native HttpClient version

### ISSUE THREAD

**Issue by booniepepper** [PawelAdamski/HttpClientMock#45]
Hi there!

I came across a related project called HttpClientMock that you were also involved in: https://github.com/PGSSoft/HttpClientMock/issues/3

This project is great and from what I can tell, it's the only productive option for mocking the Java 11 native HttpClient. (Aside from rolling-your-own similar solution.)

I'm planning to fork that project in a couple weeks, unless you're interested in owning it:

https://github.com/PGSSoft/HttpClientMock/issues/3

Thanks,
J.R.

**Comment by PawelAdamski** [comment]
Hi @booniepepper 
I will continue to maintain the library.

**Comment by booniepepper** [comment]
Great thanks. I'll delete my proposed fork
